### ISSUE TITLE
witherspoon phosphor-health-monitor[194]: Error from statvfs2

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-health-monitor#1]
I noticed our HW CI machine (witherspoon) as well as our QEMU model of witherspoon has started showing this repeatedly in the journal using the latest master code:

```
Nov 19 20:14:04 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:05 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:06 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:07 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:08 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:09 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:10 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:11 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:12 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:13 witherspoon phosphor-health-monitor[194]: Error from statvfs2
Nov 19 20:14:14 witherspoon phosphor-health-monitor[194]: Error from statvfs2
```

Probably related to af9acbde4b4d782d78fc8af30059207974bcc186 @Bruceleequantatw ?

**Comment by Bruceleequantatw** [comment]
please check the bmc_health_config.json and the sensor corresponding "path" is correct, you can reference the bellow example, need to use **Mounted on**  path with your filesystem's in  bmc_health_config.json "path".

i.e.
Filesystem           1K-blocks      Used     Available     Use%     Mounted on
dev                      179840                0       179840         0%      /dev
tmpfs                   213668        12040       201628         6%      /run
/dev/mtdblock4    19072        19072                 0     100%      /run/initramfs/ro
/dev/mtdblock5      4096            364           3732         9%      **/run/initramfs/rw**

bmc_health_config.json
"Storage_RW" : {
    "Path" : "**/run/initramfs/rw**",
    "Frequency" : 1,
    "Window_size": 120,
    "Threshold":
    {
        "Critical":
        {
            "Value": 85.0,
            "Log": true,
            "Target": "reboot.target"
        }
    }
  },

**Comment by geissonator** [comment]
We've just gotten phosphor-health-monitor by default on our system since it's a part of the base phosphor package. I don't think the lack of a config file should cause this type of constant warning to the journal? If the file is not present or the directory is missing,  could it just do nothing? This currently fills our journal up very quickly which prevents other debug.

Our witherspoon systems use a UBI filesystem
```
root@witherspoon-Y230UF71K03T:~# df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root                19712     19712         0 100% /
devtmpfs                180892         0    180892   0% /dev
ubi0:rwfs                 4644      1892      2752  41% /var
overlay                   4644      1892      2752  41% /etc
tmpfs                   214172         8    214164   0% /dev/shm
tmpfs                    85672       984     84688   1% /run
tmpfs                     4096         0      4096   0% /sys/fs/cgroup
tmpfs                   214172        84    214088   0% /tmp
ubi0:rwfs                 4644      1892      2752  41% /home
tmpfs                   214172         0    214172   0% /media
tmpfs                   214172         0    214172   0% /usr/local
tmpfs                   214172         0    214172   0% /var/volatile
overlay                 214172         0    214172   0% /srv
/dev/ubiblock8_0         23296     23296         0 100% /media/pnor-ro-224cd310
```

**Comment by Bruceleequantatw** [comment]
Your config not has "/run/initramfs/rw", so with the default config, it will cause this error message on your journal, this error message is code-reviewer ask me to add to reminder user their config was setting error, for now, please use a bbappend to overwrite the  bmc_health_config.json, if you don't need to monitor the storage/inode utilization, please remove it on your config, I will discuss with the code-reviewer what is the best with the default setting in bmc_health_config.json

**Comment by bradbishop** [comment]
It would be great to see this change get reverted once this issue is fixed:

https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/38444

I have to say - I think we are walking on a slippery slope here by writing code that doesn't work everywhere...this leads to fragmentation that OpenBMC is already plagued by.

What do I mean by code that works everywhere? - for example I think in this case we could have logged that the directory to be monitored does not exist once at application start, and the program would simply ignore that configuration entry.

**Comment by geissonator** [comment]
I put https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/38811 up to revert the removal for IBM systems now that this is fixed. Thanks!
