### ISSUE TITLE
Enable async https request with boost::beast inside healthMonitor.cpp(enabling threads)

### ISSUE THREAD

**Issue by paulnegz** [openbmc/phosphor-health-monitor#2]
OS: Ubuntu bionic
```
    resolver_.async_resolve(
        host,
        port,
        beast::bind_front_handler(
            &session::on_resolve,
            shared_from_this()));
}
```
using meson build system (https://mesonbuild.com/).  Resolver_.async_resolve is a c++ method from (tcp::resolver resolver_ object; https://github.com/boostorg/beast/tree/develop/example/http/client/async-ssl) which is a required method to call in order to make an async http request using boost libraries(https://www.boost.org/) .

async http example works in separate .cpp file but not inside healthMonitor.cpp

After attaching the header files and libraries, I am unable to make a http request inside healthMonitor.cpp
![ERROR](https://user-images.githubusercontent.com/37233089/125712789-17cd4d71-0add-48e9-a4ea-1ec455e70226.JPG)

Attached Dependencies: 
![mesonEdit](https://user-images.githubusercontent.com/37233089/125712258-6a48c0c4-7897-4c92-b392-a00dd8a30f17.JPG)

**Comment by williamspatrick** [comment]
I’m not sure why you would be trying to do this or why you’d expect someone on an unrelated package be able to tell you how to debug something with a new library you are trying to use… but, I think there are boost compile flags you need to enable what you’re trying to do. Please check bmcweb’s boost flags and maybe sdbusplus’s for hints.
